[package]
name = "tracer"
version = "0.1.0"
authors = ["Nick Young <youngnicholas228@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
